# docker-compose.yml
version: "3"
services:
    db:
        build:
            context: ./docker/
            dockerfile: DB.dockerfile
        image: robert2/api-db:latest
        ports:
            - "33060:3306"
    web:
        build:
            context: ./docker/
            dockerfile: WEB.dockerfile
        image: robert2/api-web:latest
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - .:/app
        links:
            - "db:database"
